#
# This source file is part of the ENGAGE-HF Android open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: documentation
  cancel-in-progress: false

jobs:
  dokka:
    name: Dokka Documentation Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
      - name: Build Documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
